### PR TITLE
Issue 30 - Modify POST request in signup.js

### PR DESCRIPTION
**Pull request by sleepyStick**
I believe this works! but I didn't test it (yesterday you mentioned not being able to run the backend so i didn't try today)

Thank you!

### CODE REVIEW

**Review by QueMona98 — CHANGES_REQUESTED** [review]
Great! Also you can just remove the check for admin -- there is only one admin and I don't want to add an option to sign up as admin. Super minor fix, but if you could delete that and resubmit your pull request, it would be much appreciated!

**Comment by sleepyStick** [comment]
check for admin has been removed! let me know if I did it wrong or if there's anything else you'd like to change! :)

**Comment by QueMona98** [comment]
Again -- this all looks amazing. But can you do me another favor and resolve the merge conflict. You should be able to do this by pulling the latest code and then making another pull request. Let me know if you have any issues doing so.

**Comment by sleepyStick** [comment]
Hi, sorry i didnt notice that there were merge conflicts! they should be fixed now! Sorry about that!

**Review by QueMona98 — APPROVED** [review]

**Pull request merged**
